controllers:
    resource: ../../src/Controller/
    type: annotation

kernel:
    resource: ../../src/Kernel.php
    type: annotation
    
bundle:
    resource: "@HcrispensAuthBundle/Controller/"
    type: annotation
